# XHTTP 伪装站设置
server {
    listen                  unix:/dev/shm/nginx/cdn_to_nginx.sock ssl backlog=2048 so_keepalive=on proxy_protocol;
    http2                   on;

    set_real_ip_from        unix:;
    # https://www.cloudflare.com/ips-v4/#
    set_real_ip_from        173.245.48.0/20;
    set_real_ip_from        103.21.244.0/22;
    set_real_ip_from        103.22.200.0/22;
    set_real_ip_from        103.31.4.0/22;
    set_real_ip_from        141.101.64.0/18;
    set_real_ip_from        108.162.192.0/18;
    set_real_ip_from        190.93.240.0/20;
    set_real_ip_from        188.114.96.0/20;
    set_real_ip_from        197.234.240.0/22;
    set_real_ip_from        198.41.128.0/17;
    set_real_ip_from        162.158.0.0/15;
    set_real_ip_from        104.16.0.0/13;
    set_real_ip_from        104.24.0.0/14;
    set_real_ip_from        172.64.0.0/13;
    set_real_ip_from        131.0.72.0/22;
    # https://www.cloudflare.com/ips-v6/#
    set_real_ip_from        2400:cb00::/32;
    set_real_ip_from        2606:4700::/32;
    set_real_ip_from        2803:f800::/32;
    set_real_ip_from        2405:b500::/32;
    set_real_ip_from        2405:8100::/32;
    set_real_ip_from        2a06:98c0::/29;
    set_real_ip_from        2c0f:f248::/32;

    real_ip_header          CF-Connecting-IP;

    server_name             <XHTTP_CDN_Site>;
    root                    /var/www/<XHTTP_CDN_Site>;

    # SSL
    ssl_certificate         /etc/nginx/ssl/<XHTTP_CDN_Site>/fullchain.cer;
    ssl_certificate_key     /etc/nginx/ssl/<XHTTP_CDN_Site>/private.key;
    ssl_trusted_certificate /etc/nginx/ssl/<XHTTP_CDN_Site>/ca.cer;
    ssl_early_data          on;

    include                 /etc/nginx/nginxconfig.io/security.conf;

    # logging
    access_log              /var/log/nginx/access.log custom buffer=512k flush=1m;
    error_log               /var/log/nginx/error.log warn;

    location / {
        index               index.html;
    }

    # additional config
    include                 /etc/nginx/nginxconfig.io/general.conf;

    # 以下参数请根据服务器内存大小自行调整
    http2_max_concurrent_streams 1024;
    http2_body_preread_size      128k;
    keepalive_time               2h;
    keepalive_timeout            600s;
    keepalive_requests           2048;
    client_body_buffer_size      1m;
    client_body_timeout          600s;
    client_header_timeout        300s;
    large_client_header_buffers  8 16k;
    proxy_connect_timeout        30s;
    proxy_read_timeout           2h;
    proxy_send_timeout           2h;
    proxy_buffering              off;
    proxy_request_buffering      off;

    # xhttp 设置
    location /<XHTTP_PATH> {
        grpc_pass                grpc://unix:/dev/shm/nginx/to_xray_xhttp.sock;

        grpc_buffer_size         128k;
        grpc_socket_keepalive    on;
        grpc_read_timeout        1h;
        grpc_send_timeout        1h;

        grpc_set_header Connection        "";
        grpc_set_header X-Real-IP         $remote_addr;
        grpc_set_header Forwarded         $proxy_add_forwarded;
        grpc_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;
        grpc_set_header X-Forwarded-Host  $host;
        grpc_set_header X-Forwarded-Port  $server_port;
        grpc_set_header Host              $http_host;
        grpc_set_header Early-Data        $ssl_early_data;
    }

    location = /<Subs_Site_PATH> {
        alias /var/www/subscription/subs.txt;
        charset utf-8;
        # 强制设置浏览器识别为纯文本
        default_type text/plain;
        # 明确告诉浏览器在页内展示
        add_header Content-Disposition "inline";
    }
}